language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "esc-test";' -U postgres
script:
- npm test
- npm run build-client
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: lets-esc
  api_key:
    secure: GY2yghQcQAdQh6OTXb9DqP8vEdc5H3XmpE2e6PZNPajSIHhBBWlZDUPLxZQnuZOoX+W8/dxCQppYN5KWNzVTqd94FXotjsJzzIBDy56caolMAFmaU1elAVDI2Iw3U3fF/2Ici0GIvN0TIRt7nhKQrcMntMURIo3CyR8TDEqFnY6/VGk+SPDkhupJXbKAYlFIO/zOCzfNNNfRiDI2pokw+Id35ea3udf2J2kzJ5j+G1AjZxcabhP7j0gN2gK/I9JaMYSSp0StwGw+IUQ4aOqSMiZvLFauAWbjCJ0UCsBHX0fgl05Ssis26s5PJNOGHRmZBBrPPZHWK5fEGN51W5Lbf8sqcAxBNBc8hdrCRdaaOcOrkgr1/eMZ0ZOM1IZqKvE9Fn95gyohgT0CHLmS58qQIO0ucSdqGfgNp08a4VTQuzx23dM9SVP++fLeWbeiIBSFZ6TOukoUAiR7dVyem5drHQG+rilBLFaOsFQ/zfxhLLSQeuCdhpBbHFc236ltV/bqhEIGSCgraozqDZnJTeNcgILJKl1R52Lx5X/zPMhMyQNSXsy5fXOoawD87Tvp+WycgMMDnauntR3s3aPztHulSoXT0EYANTSf4GTFRu/s0xuxGZoePeLSbwzhbj/x5Hked6Q9EGwIaAB2tjYYlrcMO9Rz5Y6jTK2JyhwY00hBuCg=
